name: Pull Request
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  flake-health-checks:
    name: Nix flake health checks
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      # check the flake can be built
      - run: nix flake check
      # build flake packages
      - run: nix build .#versa
      - run: nix build .#lasr_node
      # build development shells
      - run: nix develop .#protocol-dev
      - run: nix develop .#lasr-dev
      - run: nix develop .#versa-rs
      - run: nix develop .#versa-hs

  check-digitalocean-images:
    name: Build NixOS DigitalOcean images
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: cd deployments/lasr_node/nightly && nix-build image.nix
